import { useEffect, useRef, useState, type FormEvent } from 'react';
import { ArrowLeft, ArrowRight, Archive, Building2, CheckCircle2, ChevronLeft, ChevronRight, ClipboardList, Download, FileUp, History, LockKeyhole, Pencil, Plus, RefreshCw, ShieldCheck, Upload, X } from 'lucide-react';
import { MemberError, memberRequest, useMembership } from '../membership';
import AccountDialog from '../AccountDialog';
import './admin.css';

const categories:Record<string,string>={VENUE:'예식장',STUDIO:'스튜디오',DRESS:'드레스',MAKEUP:'메이크업',JEWELRY:'예물',HANBOK:'한복',SUIT:'예복'};
type Data={externalKey:string;organizationName:string;branchName:string;category:string;region:string;address:string;publicPhone:string;sourceUrl:string};
type Draft={id:string;data:Data;status:'DRAFT'|'ARCHIVED';version:number;updatedAt:string};
type Page={items:Draft[];total:number;page:number};
type Preview={ticket:{id:string;expiresAt:string}|null;valid:boolean;rows:{row:number;data:Data|null;errors:string[]}[]};
type Audit={id:string;actorId:string;action:string;targetId:string;occurredAt:string};
const blank:Data={externalKey:'',organizationName:'',branchName:'',category:'VENUE',region:'',address:'',publicPhone:'',sourceUrl:''};
const date=(text:string)=>new Date(text).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
const messages:Record<string,string>={CATALOG_CREATE:'개별 등록',CATALOG_UPDATE:'초안 수정',CATALOG_ARCHIVE:'보관 처리',CATALOG_IMPORT:'CSV 등록'};

export default function AdminApp(){
  const [notice,setNotice]=useState('');const membership=useMembership(setNotice);
  const [account,setAccount]=useState(false);const [tab,setTab]=useState<'catalog'|'upload'|'audit'>('catalog');
  const [page,setPage]=useState(0);const [status,setStatus]=useState('');const [list,setList]=useState<Page>({items:[],total:0,page:0});
  const [audits,setAudits]=useState<Audit[]>([]);const [reload,setReload]=useState(0);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  const [editing,setEditing]=useState<Draft|'new'|null>(null);const [archiving,setArchiving]=useState<Draft|null>(null);const [busy,setBusy]=useState(false);
  const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState<Preview|null>(null);const [completed,setCompleted]=useState<number|null>(null);
  const fileInput=useRef<HTMLInputElement>(null);
  async function failed(err:unknown){setError(err instanceof Error?err.message:'요청을 처리하지 못했습니다. 다시 시도해 주세요.');if(err instanceof MemberError&&(err.status===401||err.status===403))await membership.refresh().catch(()=>{});}
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(t);},[notice]);
  useEffect(()=>{
    if(!membership.member?.admin){setList({items:[],total:0,page:0});setAudits([]);setEditing(null);setArchiving(null);setPreview(null);return;}
    let current=true;setLoading(true);setError('');
    const request=tab==='audit'?memberRequest<Audit[]>('/admin/audit').then(data=>{if(current)setAudits(data);}):memberRequest<Page>(`/admin/catalog?page=${page}&status=${status}`).then(data=>{if(current)setList(data);});
    request.catch(err=>{if(current)void failed(err);}).finally(()=>{if(current)setLoading(false);});
    return()=>{current=false;};
  },[membership.member?.id,membership.member?.admin,tab,page,status,reload]);
  function switchTab(next:typeof tab){if(busy)return;setTab(next);setError('');}
  async function save(data:Data){
    setBusy(true);try{await memberRequest(editing==='new'?'/admin/catalog':`/admin/catalog/${(editing as Draft).id}`,editing==='new'?'POST':'PUT',editing==='new'?data:{data,version:(editing as Draft).version});setEditing(null);setNotice('업체 초안을 저장했습니다. 공개 검색에는 반영되지 않습니다.');setReload(x=>x+1);}catch(err){await failed(err);throw err;}finally{setBusy(false);}
  }
  async function archive(){if(!archiving||busy)return;setBusy(true);try{await memberRequest(`/admin/catalog/${archiving.id}/archive`,'POST',{version:archiving.version});setArchiving(null);setReload(x=>x+1);setNotice('초안을 보관했습니다. 변경 이력은 유지됩니다.');}catch(err){await failed(err);}finally{setBusy(false);}}
  async function validateFile(){
    if(!file||busy)return;setBusy(true);setError('');setPreview(null);setCompleted(null);
    try{if(!file.name.toLowerCase().endsWith('.csv')||file.size>262144)throw new Error('256KB 이하 UTF-8 CSV 파일을 선택해 주세요.');const data=new FormData();data.append('file',file);setPreview(await memberRequest<Preview>('/admin/imports/preview','POST',data));}catch(err){await failed(err);}finally{setBusy(false);}
  }
  async function commit(){if(!preview?.ticket||busy)return;setBusy(true);setError('');try{const result=await memberRequest<{count:number}>(`/admin/imports/${preview.ticket.id}/commit`,'POST');setCompleted(result.count);setPreview(null);setFile(null);if(fileInput.current)fileInput.current.value='';setReload(x=>x+1);}catch(err){await failed(err);}finally{setBusy(false);}}
  const accountDialog=account?<AccountDialog member={membership.member} ephemeral={membership.ephemeral} count={membership.favorites.length} onClose={()=>setAccount(false)} onChanged={membership.refresh} notify={setNotice}/>:null;
  if(!membership.ready)return <main className="admin-gate"><ShieldCheck size={34}/><h1>관리자 권한을 확인하고 있습니다.</h1></main>;
  if(!membership.available)return <main className="admin-gate"><ShieldCheck size={34}/><h1>서버 연결을 확인해 주세요</h1><p>권한을 확인하기 전에는 관리 데이터를 표시하지 않습니다.</p><button className="primary" onClick={()=>membership.refresh().catch(()=>{})}>다시 연결</button><a href="/">회원 화면으로 돌아가기</a></main>;
  if(!membership.member?.admin)return <><main className="admin-gate"><div className="admin-gate-brand">연 <small>ADMIN</small></div><LockKeyhole size={34}/><h1>{membership.member?'관리자 권한이 필요합니다':'운영 관리에 로그인하세요'}</h1><p>업체 정보와 업로드 자료는 관리자만 조회·수정할 수 있습니다.<br/>{membership.member?'현재 계정에는 관리자 권한이 없습니다.':'발급받은 관리자 계정으로 로그인해 주세요.'}</p><button className="primary" onClick={()=>setAccount(true)}>{membership.member?'계정 확인·로그아웃':'관리자 로그인'}<ArrowRight size={16}/></button><a href="/"><ArrowLeft size={13}/>회원 화면으로</a></main>{accountDialog}</>;
  return <div className="admin-shell">
    <aside className="admin-sidebar"><a href="/admin" className="admin-logo">연 <span>ADMIN</span></a><div className="admin-sidebar-label">운영 워크스페이스</div><nav aria-label="관리 메뉴">{([{key:'catalog',name:'업체 초안',icon:Building2},{key:'upload',name:'데이터 업로드',icon:Upload},{key:'audit',name:'변경 이력',icon:History}] as const).map(({key,name,icon:Icon})=><button disabled={busy} className={tab===key?'active':''} key={key} onClick={()=>switchTab(key)}><Icon size={18}/>{name}<ChevronRight size={13}/></button>)}</nav><div className="admin-sidebar-bottom"><ShieldCheck size={19}/><strong>관리자 전용 영역</strong><p>등록 → 검증 → 초안 저장<br/>공개는 별도 검수 후 진행합니다.</p><a href="/"><ArrowLeft size={13}/>회원 화면 보기</a></div></aside>
    <div className="admin-workspace"><header className="admin-topbar"><span>YEON / OPERATIONS</span><button disabled={busy} onClick={()=>setAccount(true)}><span className="admin-avatar">관</span>{membership.member.displayName}<span className="admin-role">ADMIN</span></button></header>
      <main className="admin-main"><div className="admin-heading"><div><div className="eyebrow">CATALOG MANAGEMENT</div><h1>{tab==='catalog'?'업체 정보를 차곡차곡':tab==='upload'?'여러 업체를 한 번에 등록':'변경 내역을 확인하세요'}</h1><p>{tab==='catalog'?'기관·업체의 기본 정보를 초안으로 관리합니다.':tab==='upload'?'양식을 내려받고, 저장 전에 각 행의 검증 결과를 확인하세요.':'최근 등록·수정·보관 작업 50건을 보여줍니다.'}</p></div>{tab==='catalog'&&<button className="primary" disabled={busy} onClick={()=>{setError('');setEditing('new');}}><Plus size={17}/>업체 등록</button>}</div>
      <div className="admin-guidance"><ShieldCheck size={17}/><span>{membership.ephemeral?'체험 모드 · 서버 재시작 시 등록 데이터와 계정이 초기화됩니다.':'DB 저장 모드 · 작업 내역을 계정과 함께 보관합니다.'} 모든 등록 자료는 초안이며, 가격표·공개 승인은 후속 단계입니다.</span></div>
      {error&&<div className="admin-error" role="alert">{error}<button onClick={()=>{setError('');setReload(x=>x+1);}}><RefreshCw size={13}/>새로고침</button></div>}
      {tab==='catalog'&&<><div className="admin-stats"><div><span>현재 목록</span><strong>{list.total}<small>건</small></strong></div><div><span>지원 카테고리</span><strong>7<small>업종</small></strong></div><div><span>등록 방식</span><strong className="text">개별 등록 · CSV 업로드</strong></div></div><section className="admin-panel"><div className="admin-panel-header"><h2><ClipboardList size={17}/>업체 초안 목록</h2><div><select aria-label="초안 상태 필터" value={status} onChange={e=>{setStatus(e.target.value);setPage(0);}}><option value="">전체 상태</option><option value="DRAFT">초안</option><option value="ARCHIVED">보관됨</option></select><button aria-label="목록 새로고침" onClick={()=>setReload(x=>x+1)}><RefreshCw size={16}/></button></div></div>
      {loading?<div className="admin-empty" role="status">목록을 불러오고 있습니다.</div>:list.items.length===0?<div className="admin-empty"><Building2 size={33}/><h3>아직 등록된 초안이 없어요</h3><p>업체를 직접 등록하거나 CSV 파일로 가져와 보세요.</p><button className="secondary" onClick={()=>switchTab('upload')}>CSV로 가져오기 <ArrowRight size={14}/></button></div>:<div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>업체 · 지점</th><th>카테고리</th><th>지역</th><th>상태</th><th>최근 수정</th><th>관리</th></tr></thead><tbody>{list.items.map(d=><tr key={d.id}><td><strong>{d.data.organizationName}</strong><small>{d.data.branchName} · {d.data.externalKey}</small></td><td>{categories[d.data.category]}</td><td>{d.data.region}</td><td><span className={`admin-status ${d.status==='ARCHIVED'?'archived':''}`}>{d.status==='DRAFT'?'초안':'보관됨'}</span></td><td>{date(d.updatedAt)}<small>버전 {d.version}</small></td><td><div className="admin-row-actions"><button disabled={d.status==='ARCHIVED'||busy} aria-label={`${d.data.organizationName} 수정`} onClick={()=>{setError('');setEditing(d);}}><Pencil size={15}/></button><button disabled={d.status==='ARCHIVED'||busy} aria-label={`${d.data.organizationName} 보관`} onClick={()=>setArchiving(d)}><Archive size={15}/></button></div></td></tr>)}</tbody></table></div>}
      <div className="admin-pagination"><span>페이지당 20건 · {page+1}페이지</span><div><button disabled={page===0||loading} onClick={()=>setPage(p=>p-1)} aria-label="이전 페이지"><ChevronLeft size={16}/></button><button disabled={(page+1)*20>=list.total||loading} onClick={()=>setPage(p=>p+1)} aria-label="다음 페이지"><ChevronRight size={16}/></button></div></div></section></>}
      {tab==='upload'&&<><div className="admin-steps"><span><b>1</b>양식 다운로드</span><i/><span><b>2</b>파일 검증</span><i/><span><b>3</b>초안 저장</span></div><section className="admin-panel admin-upload"><div className="admin-upload-copy"><FileUp size={35}/><h2>업체 CSV 파일 업로드</h2><p>UTF-8 CSV · 최대 256KB · 최대 100행<br/>예식장부터 예복까지, 7개 업종을 함께 등록할 수 있습니다.</p><a className="secondary" href="/api/v1/admin/imports/template" download><Download size={15}/>등록 양식 다운로드</a></div><div className="admin-file-select"><label htmlFor="catalog-file">업체 정보 파일</label><input id="catalog-file" ref={fileInput} type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]??null);setPreview(null);setCompleted(null);setError('');}}/><small>출처 URL은 참고 정보로만 저장하며 자동으로 접속하지 않습니다.</small><button className="primary" disabled={!file||busy} onClick={validateFile}>{busy?'처리 중…':'파일 검증·미리보기'}<ArrowRight size={15}/></button></div></section>
        {completed!==null&&<div className="admin-success" role="status"><CheckCircle2 size={23}/><div><strong>{completed}개 업체를 초안으로 저장했습니다.</strong><p>공개 검색 데이터는 변경하지 않았습니다.</p></div><button onClick={()=>{setStatus('');setPage(0);switchTab('catalog');}}>등록 목록 보기 <ArrowRight size={14}/></button></div>}
        {preview&&<section className="admin-panel"><div className="admin-panel-header"><h2>검증 결과 <span>{preview.rows.length}행</span></h2><span className={`admin-status ${preview.valid?'':'archived'}`}>{preview.valid?'모든 행 검증 완료':'오류 수정 필요'}</span></div><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>CSV 행</th><th>업체</th><th>관리 코드</th><th>검증 결과</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.data?.organizationName??'읽기 실패'}<small>{r.data?.branchName}</small></td><td>{r.data?.externalKey??'—'}</td><td>{r.errors.length?r.errors.map((x,i)=><p className="admin-row-error" key={i}>{x}</p>):<span className="admin-valid"><CheckCircle2 size={13}/>등록 가능</span>}</td></tr>)}</tbody></table></div><div className="admin-preview-footer"><p>{preview.ticket?`미리보기 유효 시간: ${date(preview.ticket.expiresAt)}까지. 저장 시 중복 여부를 다시 확인합니다.`:'한 행이라도 오류가 있으면 저장되지 않습니다. 파일을 수정하고 다시 검증해 주세요.'}</p><button className="primary" disabled={!preview.valid||!preview.ticket||busy} onClick={commit}>{busy?'저장 중…':`${preview.rows.length}개 초안으로 저장`}<CheckCircle2 size={15}/></button></div></section>}
        <div className="admin-help"><h3>양식 작성 기준</h3><p><b>externalKey</b>는 중복되지 않는 영문 소문자·숫자·하이픈·밑줄 3~80자입니다. 업체명, 지점명, 업종, 지역, 주소는 필수입니다.</p><p><b>category</b>: VENUE / STUDIO / DRESS / MAKEUP / JEWELRY / HANBOK / SUIT</p><p>동일 관리 코드 또는 업체명·지점·업종·주소가 겹치면 등록을 중단합니다. 기존 데이터를 CSV로 덮어쓰지 않습니다.</p></div></>}
      {tab==='audit'&&<section className="admin-panel"><div className="admin-panel-header"><h2><History size={17}/>최근 변경 이력</h2><button aria-label="이력 새로고침" onClick={()=>setReload(x=>x+1)}><RefreshCw size={16}/></button></div>{loading?<div className="admin-empty">이력을 불러오는 중입니다.</div>:audits.length===0?<div className="admin-empty"><History size={30}/><h3>아직 변경 내역이 없습니다.</h3></div>:<div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>시각</th><th>작업</th><th>대상 ID</th><th>관리자 ID</th></tr></thead><tbody>{audits.map(a=><tr key={a.id}><td>{date(a.occurredAt)}</td><td>{messages[a.action]??a.action}</td><td className="admin-id">{a.targetId}</td><td className="admin-id">{a.actorId}</td></tr>)}</tbody></table></div>}</section>}
      <footer className="admin-footer">YEON OPERATIONS<span>업체 기본 정보 초안 · 가격표와 공개 심사는 별도 단계</span></footer></main></div>
    {editing&&<DraftEditor draft={editing==='new'?null:editing} busy={busy} onClose={()=>setEditing(null)} onSave={save}/>}
    {archiving&&<ArchiveDialog draft={archiving} busy={busy} onClose={()=>setArchiving(null)} onConfirm={archive}/>}
    {accountDialog}{notice&&<div className="toast" role="status">{notice}</div>}
  </div>;
}

function DraftEditor({draft,busy,onClose,onSave}:{draft:Draft|null;busy:boolean;onClose:()=>void;onSave:(data:Data)=>Promise<void>}){
  const [data,setData]=useState<Data>(draft?.data??{...blank});const [error,setError]=useState('');const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{dialog.current?.showModal();},[]);
  async function submit(event:FormEvent){event.preventDefault();if(busy)return;setError('');try{await onSave(data);}catch(err){setError(err instanceof Error?err.message:'저장에 실패했습니다.');}}
  return <dialog className="admin-editor" ref={dialog} aria-labelledby="draft-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><button className="dialog-close" onClick={onClose} disabled={busy} aria-label="등록 창 닫기"><X size={20}/></button><div className="eyebrow">CATALOG DRAFT</div><h2 id="draft-title">{draft?'업체 초안 수정':'새 업체 등록'}</h2><p className="admin-editor-note">기관·사업 주체와 실제 지점 정보를 나누어 입력합니다.</p><form onSubmit={submit}><fieldset disabled={busy}><label>관리 코드<input required pattern="[a-z0-9][a-z0-9_-]{2,79}" maxLength={80} placeholder="예: maison-gangnam" value={data.externalKey} onChange={e=>setData({...data,externalKey:e.target.value})}/><small>영문 소문자·숫자·하이픈·밑줄 3~80자</small></label><div className="admin-form-grid"><label>기관·업체명<input required maxLength={120} value={data.organizationName} onChange={e=>setData({...data,organizationName:e.target.value})}/></label><label>지점명<input required maxLength={100} value={data.branchName} onChange={e=>setData({...data,branchName:e.target.value})}/></label><label>카테고리<select value={data.category} onChange={e=>setData({...data,category:e.target.value})}>{Object.entries(categories).map(([code,name])=><option value={code} key={code}>{name}</option>)}</select></label><label>지역<input required maxLength={60} placeholder="예: 서울 강남" value={data.region} onChange={e=>setData({...data,region:e.target.value})}/></label></div><label>주소<input required maxLength={250} value={data.address} onChange={e=>setData({...data,address:e.target.value})}/></label><label>공개 연락처 <small>선택</small><input type="tel" maxLength={30} value={data.publicPhone} onChange={e=>setData({...data,publicPhone:e.target.value})}/></label><label>출처 URL <small>선택</small><input type="url" maxLength={1000} placeholder="https://" value={data.sourceUrl} onChange={e=>setData({...data,sourceUrl:e.target.value})}/></label>{error&&<p className="admin-row-error" role="alert">{error}</p>}<p className="admin-editor-note">초안은 관리자에게만 표시됩니다. 실제 가격·서비스 조건은 별도로 검수합니다.</p><button className="primary full" type="submit">{busy?'저장 중…':'초안 저장'}<CheckCircle2 size={16}/></button></fieldset></form></dialog>;
}
function ArchiveDialog({draft,busy,onClose,onConfirm}:{draft:Draft;busy:boolean;onClose:()=>void;onConfirm:()=>void}){
  const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{dialog.current?.showModal();},[]);
  return <dialog ref={dialog} aria-labelledby="archive-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><h2 id="archive-title">초안을 보관할까요?</h2><p className="admin-editor-note">{draft.data.organizationName} · {draft.data.branchName}<br/>보관 후에는 수정할 수 없습니다. 데이터와 변경 이력은 남아 있습니다.</p><div className="admin-confirm-actions"><button className="secondary" disabled={busy} onClick={onClose}>취소</button><button className="primary" disabled={busy} onClick={onConfirm}>{busy?'처리 중…':'보관하기'}</button></div></dialog>;
}
