import {useEffect,useState,type FormEvent} from 'react';
import Brand from './Brand';
import {catalogCategories} from './catalog';
import {memberRequest,useMembership} from './membership';
import AccountDialog from './AccountDialog';
import './directory.css';

type Entry={id:string;organizationName:string;branchName:string;category:string;region:string;address:string;publicPhone:string;sourceUrl:string;reviewedOn:string};
export default function DirectoryApp(){
  const [notice,setNotice]=useState(''),[accountOpen,setAccountOpen]=useState(false),[onlySaved,setOnlySaved]=useState(false);
  const membership=useMembership(setNotice);
  const [category,setCategory]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState({category:'',query:''}),[page,setPage]=useState(0),[retry,setRetry]=useState(0);
  const [loading,setLoading]=useState(true),[error,setError]=useState('');
  const [data,setData]=useState<{items:Entry[];total:number;persistent:boolean}>({items:[],total:0,persistent:true});
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer);},[notice]);
  useEffect(()=>{let active=true;setLoading(true);setError('');if(onlySaved&&(!membership.member||!membership.available)){setData({items:[],total:0,persistent:true});setLoading(false);return;}
    const params=new URLSearchParams({...filter,page:String(page)});memberRequest<typeof data>(`${onlySaved?'/me/directory':'/directory'}?${params}`).then(r=>{if(active)setData(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[filter,page,retry,onlySaved,membership.member?.id,membership.available,membership.favorites.join(',')]);
  function submit(e:FormEvent){e.preventDefault();setPage(0);setFilter({category,query});}
  async function favorite(id:string){if(!membership.member){setAccountOpen(true);return;}await membership.favorite(id);}
  return <div className="directory-shell"><header className="directory-header"><a href="/" aria-label="All About Wedding 홈"><Brand/></a><nav><a href="/preview/venues">예식장 견적 체험</a><button disabled={!membership.ready} onClick={()=>setAccountOpen(true)}>{membership.member?`${membership.member.displayName}님`:'로그인 · 회원가입'}</button>{membership.member?.admin&&<a href="/admin">관리자</a>}</nav></header><main className="directory-main"><div className="eyebrow">WEDDING DIRECTORY</div><h1>우리의 결혼을 함께할 곳</h1><p className="directory-intro">예식장부터 본식 촬영까지, 출처를 확인한 업체 정보를 한곳에서 살펴보세요.</p>
    <p className="catalog-demo-link"><a href="/preview/catalog">업종별 가상 업체 20곳 미리 둘러보기 →</a></p><div className="directory-tabs"><button className={!onlySaved?'active':''} onClick={()=>{setOnlySaved(false);setPage(0);}}>전체 업체</button><button className={onlySaved?'active':''} disabled={!membership.ready||!membership.available} onClick={()=>{if(!membership.member){setAccountOpen(true);return;}setOnlySaved(true);setPage(0);}}>내 계정 찜</button></div>
    {membership.ready&&!membership.available&&<p className="directory-notice" role="alert">회원 저장소에 연결하지 못했습니다. 찜 저장은 연결 복구 후 이용할 수 있습니다. <button onClick={()=>membership.refresh().catch(()=>{})}>다시 연결</button></p>}
    {onlySaved&&<p className="directory-notice">로그인한 계정의 찜 중 현재 공개된 실제 업체를 보여줍니다. 가상 예식장 찜은 견적 체험 화면에서 확인할 수 있습니다.</p>}
    <form className="directory-filters" onSubmit={submit}><label>업종<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">모든 업종</option>{Object.entries(catalogCategories).map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><label>업체명 · 지역<input maxLength={100} placeholder="찾고 있는 업체나 지역" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="primary">찾아보기</button></form>
    <p className="directory-notice">업체 상세에서 등록된 사진·주차 조건·날짜별 참고 견적을 확인하세요. 예약 가능 여부와 확정 금액은 업체 확인이 필요합니다.</p>
    {!data.persistent&&<p className="directory-notice">체험 모드 · 공개 업체 저장소가 연결되지 않은 개발 환경입니다.</p>}
    {loading?<section className="empty" role="status">업체 정보를 불러오고 있습니다.</section>:error?<section className="empty" role="alert"><h2>목록을 불러오지 못했습니다</h2><p>{error}</p><button className="secondary" onClick={()=>setRetry(x=>x+1)}>다시 시도</button></section>:<><p className="directory-count">공개 업체 {data.total}곳</p>{data.items.length===0?<section className="directory-empty"><h2>{onlySaved?'아직 찜한 공개 업체가 없습니다':'아직 공개된 업체가 없습니다'}</h2><p>{onlySaved?'전체 업체에서 마음에 드는 곳을 내 계정에 저장해 보세요.':'업체 정보를 확인하고 있습니다. 검수를 마친 업체부터 이곳에 공개됩니다.'}</p><button className="secondary" onClick={()=>{setCategory('');setQuery('');setPage(0);setFilter({category:'',query:''});}}>전체 업종 보기</button></section>:<div className="directory-grid">{data.items.map(e=><article className="directory-card" key={e.id}><span className="directory-category">{catalogCategories[e.category]}</span><button className="directory-favorite" disabled={!membership.ready||!membership.available||membership.saving} aria-pressed={membership.favorites.includes(e.id)} aria-label={`${e.organizationName} ${membership.favorites.includes(e.id)?'찜 해제':'찜하기'}`} onClick={()=>favorite(e.id)}>{membership.favorites.includes(e.id)?'♥ 찜한 업체':'♡ 내 계정에 찜'}</button><h2><a href={`/directory/${e.id}`}>{e.organizationName}</a></h2><p>{e.branchName} · {e.region}</p><dl><dt>주소</dt><dd>{e.address}</dd><dt>연락처</dt><dd>{e.publicPhone||'공개 연락처 미등록'}</dd><dt>정보 확인일</dt><dd>{e.reviewedOn}</dd></dl><a href={`/directory/${e.id}`} className="directory-detail-link">사진·주차·참고 견적 상세 보기 →</a></article>)}</div>}<div className="directory-pagination"><button className="secondary" disabled={page===0} onClick={()=>setPage(x=>x-1)}>이전</button><span>{page+1}페이지</span><button className="secondary" disabled={(page+1)*20>=data.total} onClick={()=>setPage(x=>x+1)}>다음</button></div></>}
  </main>{accountOpen&&<AccountDialog member={membership.member} ephemeral={membership.ephemeral} count={membership.favorites.length} onClose={()=>setAccountOpen(false)} onChanged={membership.refresh} notify={setNotice}/>} {notice&&<div className="toast" role="status">{notice}</div>}</div>;
}
